### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/pops-core#92]
Steps:

1. Get this repo ready to be tagged for 1.0.0
2. Make the other repos up to date
3. Tag this repo v1.0.0
4. Use v1.0.0 in the other repos
5. Tag other repos v1.0.0
6. Announce release of 1.0.0

Todo list before tagging pops-core v1.0.0:

* [x] Complete issues in this repo with [milestone 1.0.0](https://github.com/ncsu-landscape-dynamics/pops-core/milestone/1)
* [x] Rename this repo to pops-core
* [x] Update name in rpops
* [x] Update name in r.pops.spread
* [x] Update rpops
* [x] Update r.pops.spread
* [x] Specify release policy for core, R, GRASS ("minor mostly for interfaces") - #107
* [x] Update and sync references and authors in all 3 repos - #109
* [x] Remove Makefile
* [x] Update contributing ("branches") - #107

Todo list before v1.0.0 announcement:

* [x] Update to tagged pops-core version in rpops and tag
* [x] Update to tagged pops-core version in r.pops.spread and tag
* [x] Publish r.pops.spread in GRASS GIS addons repo - https://github.com/OSGeo/grass-addons/pull/269
* [x] Update image in [pops-intro-grass-notebook](https://github.com/ncsu-landscape-dynamics/pops-intro-grass-notebook/) - merge https://github.com/ncsu-landscape-dynamics/pops-intro-grass-notebook/pull/1

**Comment by wenzeslaus** [comment]
I created draft of release for this repo. I made use of the fact that any title can be provided (simple version number, project name, etc.) and used the name PoPS, i.e., PoPS 1.0.0, and described the release as release of the core and the interfaces. The other repos would have the same titles then. I did that to make clear there is one release, but in case it creates confusion, let's not do that.

**Comment by ChrisJones687** [comment]
This sounds very reasonable and I hope doesn't cause any issues.

**Comment by wenzeslaus** [comment]
Not according to the plan, but already putting our versioning strategy to the test. I had less tests for r.pops.spread then I though and had to do 1.0.1 already.

https://github.com/ncsu-landscape-dynamics/r.pops.spread/releases

I don't think it should change anything. For the announcement, we can use 1.0 or, I think, still 1.0.0 whatever makes more sense.
